customer_name=input("Enter your name: ")
drink_name=input("Enter the drink name: ")
drink_size=input("Enter the size: ")
spec_req=input("Enter a specific requirement: ")
order_num = input("Enter the order number: ")

print("\n\n ===================================")
print("           THE CODER'S CAFE")
print("\n\n ===================================")
print()
print("Order #:    " + order_num)
print("Customer:   " +customer_name)
print()
print("Drink:      "+drink_name)
print("Size:       "+drink_size)
print("Requests:   "+spec_req)
print()
print("===================================")
print("Barista Call-Out: \"One "  +drink_size+" "+drink_name+" for "+customer_name+"!\"")
print("===================================")